config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "welcome#index"
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :set_customer, only: [ :edit, :update, :show, :destroy ]
    def index
        @customers = Customer.all
    end

    def new
        @customer = Customer.new
    end

    def edit
    end

    def update
        if @customer.update(customers_params)
          redirect_to customer_path(@customer.id), notice: "Cliente atualizado com sucesso!"
        else
            render :edit
        end
    end

    def create
        @customer = Customer.new(customers_params)

        if @customer.save
          redirect_to customers_path, notice: "Cliente cadastrado com sucesso!"

        else
            render :new
        end
    end

    def show
    end

    def destroy
        if @customer.destroy
          redirect_to customers_path, notice: "Cliente excluído com sucesso!"
        else
            render :index
        end
    end

    private

    def set_customer
        @customer = Customer.find(params[:id])
    end

    def customers_params
        params.require(:customer).permit(
            :name,
            :email,
            :smoker,
            :phone,
            :avatar
        )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<% if @customer.errors.any? %>
  <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>Editando Cliente</h1>

<%= form_for @customer do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>
    
    <%= f.label :phone %>
    <%= f.text_field :phone %>

    <%= f.label :avatar %>
    <%= f.file_field :avatar %>

    <%= f.label :smoker %>
    <% {'S': 'Sim', 'N': 'Não'}.each do |key, value| %>
      <%= f.radio_button :smoker, key%> <%= value %> <br /> 
    <% end %>

    <%= f.submit 'Atualizar Cliente' %>
<% end %>

app/views/customers/index.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<h1>Listando Clientes</h1>
<table>
    <thead>
        <tr>
            <td>Nome</td>
            <td></td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        <% @customers.each do |customer| %>
        <tr>
            <td><%= customer.name %>% </td>
            <td><%= link_to "Mostrar", customer_path(customer) %></td>
            <td><%= link_to "Editar", edit_customer_path(customer) %></td>
            <td><%= link_to "Excluir", customer,
                method: :delete %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= link_to "Novo Cliente", new_customer_path %>

app/views/customers/new.html.erb
<% if @customer.errors.any? %>
  <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>Novo Cliente</h1>

<%= form_for @customer do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>
    
    <%= f.label :phone %>
    <%= f.text_field :phone %>

    <%= f.label :avatar %>
    <%= f.file_field :avatar %>

    <%= f.label :smoker %>
    <% {'S': 'Sim', 'N': 'Não'}.each do |key, value| %>
      <%= f.radio_button :smoker, key%> <%= value %> <br /> 
    <% end %>

    <%= f.submit 'Criar Cliente' %>
<% end %>

app/views/customers/show.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<h1>Mostrando Cliente</h1>

<p>
    <strong>Nome</strong>
    <%= @customer.name %>
</p>

<p>
    <strong>Email</strong>
    <%= @customer.email %>
</p>

<p>
    <strong>Telefone</strong>
    <%= @customer.phone %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tdd App V2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Seja Bem-Vindo!!!</h1>

<ul>
  <li><%= link_to "Cadastro de Clientes", customers_path %></li>
</ul>